version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: safepassword
      POSTGRES_DB: mydb

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres