version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: safepassword
      POSTGRES_DB: mydb

  app:
    build: .
    ports:
      - "5000:5000"
    restart: on-failure
    environment:
      - POSTGRESQL_CONNECTION_STRING=postgresql+psycopg2://postgres:safepassword@db:5432/mydb
    command: ["python", "./run.py"]